# Generated by Django 5.1.4 on 2024-12-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
